### PR TITLE
Add hitSlop to cancel button

### PR DESCRIPTION
**Pull request by jamesholcomb**

### CODE REVIEW

**Comment by jamesholcomb** [comment]
Can the PR be merged?

**Comment by bviebahn** [comment]
Sorry for the late reply. I'm not sure if this is needed. Maybe it would be better to add more customization options for the cancel button or the option to pass a custom component. Unfortunately I don't have much time at the moment, but I can probably find some time in the next few days. Or you can submit another PR if you like. What do you think?

**Comment by jamesholcomb** [comment]
The cancel button needs some sort of margin|padding or hitSlop applied to increase the HitRect.   It's currently limited to being pressed exactly on the Cancel text.

**Comment by bviebahn** [comment]
I just released version 1.2.3 which includes your PR. Thanks!

**Pull request merged**
